


create table if not exists author
(
    author_id                 bigint generated by default as identity 
    	primary key,
    name					varchar(255) not null,
    date_of_birthday               date not null,
    surname                 varchar(255) not null,
    second_name                   varchar(255) not null
);

create table if not exists book
(
    book_id bigint generated by default as identity 
    	primary key,
    name         varchar(255) not null
        constraint not_empty_name CHECK ( length(name) > 0),
    public_date		int,
    isbn 			bigint not null
);

create table if not exists book2author
(
    book_id bigint not null
        constraint book2author_book_id
            references book,
    author_id bigint not null
        constraint book2author_author_id
            references author,
    primary key (book_id, author_id)
);

--drop table book2author;
--drop table author;
--drop table book;



